# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotdocker2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chatbotdocker2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0e27e17da5d84b318fd0238a7c3331b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e4296dbb3c3b43948ff8882bcdd238e1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chatbotdocker2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0e27e17da5d84b318fd0238a7c3331b7 }}/chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotdocker2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_95f8eb555d534286b182fd29336dadc2 }}
        images: 'chatbotdocker2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0e27e17da5d84b318fd0238a7c3331b7 }}/chatbot:${{ github.sha }}'